
[functions.generate-document]
enabled = true
verify_jwt = false
import_map = "./functions/generate-document/deno.json"
entrypoint = "./functions/generate-document/index.ts"

[functions.analizar-voucher]
enabled = true
verify_jwt = false
entrypoint = "./functions/analizar-voucher/index.ts"
