-- FUENTE DE VERDAD DEL ESQUEMA (proporcionado por el usuario)
-- Script SQL ejecutable (solo lectura)

WITH schema_reference(table_name, column_name, data_type) AS (
  VALUES
    ('allergies', 'allergy_type', 'character varying'),
    ('allergies', 'student_id', 'uuid'),
    ('allergies', 'created_by', 'uuid'),
    ('allergies', 'notes', 'text'),
    ('allergies', 'id', 'uuid'),
    ('allergies', 'severity', 'character varying'),
    ('allergies', 'created_at', 'timestamp without time zone'),
    ('alumnos', 'foto_url', 'text'),
    ('alumnos', 'tope_diario', 'numeric'),
    ('alumnos', 'created_at', 'timestamp with time zone'),
    ('alumnos', 'seccion', 'text'),
    ('alumnos', 'codigo_interno', 'text'),
    ('alumnos', 'id', 'uuid'),
    ('alumnos', 'padre_id', 'uuid'),
    ('alumnos', 'saldo_actual', 'numeric'),
    ('alumnos', 'grado', 'text'),
    ('alumnos', 'alergias', 'text'),
    ('alumnos', 'nombres', 'text'),
    ('assets_inventory', 'model', 'text'),
    ('assets_inventory', 'brand', 'text'),
    ('assets_inventory', 'category', 'text'),
    ('assets_inventory', 'code', 'text'),
    ('assets_inventory', 'purchase_date', 'date'),
    ('assets_inventory', 'notes', 'text'),
    ('assets_inventory', 'id', 'uuid'),
    ('assets_inventory', 'name', 'text'),
    ('assets_inventory', 'serial_number', 'text'),
    ('assets_inventory', 'image_url', 'text'),
    ('assets_inventory', 'school_id', 'uuid'),
    ('assets_inventory', 'status', 'text'),
    ('assets_inventory', 'updated_at', 'timestamp with time zone'),
    ('assets_inventory', 'purchase_price', 'numeric'),
    ('assets_inventory', 'created_at', 'timestamp with time zone'),
    ('audit_billing_logs', 'changed_by_user_id', 'uuid'),
    ('audit_billing_logs', 'created_at', 'timestamp with time zone'),
    ('audit_billing_logs', 'id', 'uuid'),
    ('audit_billing_logs', 'action_type', 'text'),
    ('audit_billing_logs', 'record_id', 'uuid'),
    ('audit_billing_logs', 'table_name', 'text'),
    ('audit_billing_logs', 'old_data', 'jsonb'),
    ('audit_billing_logs', 'school_id', 'uuid'),
    ('audit_billing_logs', 'new_data', 'jsonb'),
    ('audit_logs', 'target_user_id', 'uuid'),
    ('audit_logs', 'id', 'uuid'),
    ('audit_logs', 'admin_user_id', 'uuid'),
    ('audit_logs', 'created_at', 'timestamp with time zone'),
    ('audit_logs', 'timestamp', 'timestamp with time zone'),
    ('audit_logs', 'target_user_email', 'character varying'),
    ('audit_logs', 'details', 'text'),
    ('audit_logs', 'action', 'character varying'),
    ('audit_logs_with_details', 'target_user_id', 'uuid'),
    ('audit_logs_with_details', 'target_user_email', 'character varying'),
    ('audit_logs_with_details', 'details', 'text'),
    ('audit_logs_with_details', 'id', 'uuid'),
    ('audit_logs_with_details', 'timestamp', 'timestamp with time zone'),
    ('audit_logs_with_details', 'admin_name', 'text'),
    ('audit_logs_with_details', 'admin_email', 'text'),
    ('audit_logs_with_details', 'action', 'character varying'),
    ('audit_logs_with_details', 'admin_role', 'text'),
    ('auditoria_vouchers', 'estado_ia', 'USER-DEFINED'),
    ('auditoria_vouchers', 'analisis_ia', 'jsonb'),
    ('auditoria_vouchers', 'fecha_pago_detectada', 'timestamp with time zone'),
    ('auditoria_vouchers', 'school_id', 'uuid'),
    ('auditoria_vouchers', 'monto_detectado', 'numeric'),
    ('auditoria_vouchers', 'subido_por', 'uuid'),
    ('auditoria_vouchers', 'creado_at', 'timestamp with time zone'),
    ('auditoria_vouchers', 'banco_detectado', 'character varying'),
    ('auditoria_vouchers', 'nro_operacion', 'character varying'),
    ('auditoria_vouchers', 'hash_imagen', 'text'),
    ('auditoria_vouchers', 'id', 'uuid'),
    ('auditoria_vouchers', 'url_imagen', 'text'),
    ('auditoria_vouchers', 'id_cobranza', 'uuid'),
    ('auditoria_vouchers', 'actualizado_at', 'timestamp with time zone'),
    ('auto_billing_logs', 'total_amount', 'numeric'),
    ('auto_billing_logs', 'groups_processed', 'integer'),
    ('auto_billing_logs', 'executed_at', 'timestamp with time zone'),
    ('auto_billing_logs', 'school_id', 'uuid'),
    ('auto_billing_logs', 'id', 'uuid'),
    ('auto_billing_logs', 'status', 'text'),
    ('auto_billing_logs', 'errors', 'ARRAY'),
    ('billing_config', 'serie_nc_boleta', 'text'),
    ('billing_config', 'yape_enabled', 'boolean'),
    ('billing_config', 'serie_nc_factura', 'text'),
    ('billing_config', 'direccion', 'text'),
    ('billing_config', 'plin_enabled', 'boolean'),
    ('billing_config', 'transferencia_enabled', 'boolean'),
    ('billing_config', 'demo_mode', 'boolean'),
    ('billing_config', 'razon_social', 'text'),
    ('billing_config', 'updated_by', 'uuid'),
    ('billing_config', 'enable_auto_reminders', 'boolean'),
    ('billing_config', 'updated_at', 'timestamp with time zone'),
    ('billing_config', 'id', 'uuid'),
    ('billing_config', 'school_id', 'uuid'),
    ('billing_config', 'reminder_days_before', 'integer'),
    ('billing_config', 'show_payment_info', 'boolean'),
    ('billing_config', 'cafeteria_message_template', 'text'),
    ('billing_config', 'bank_account_number', 'text'),
    ('billing_config', 'bank_cci', 'text'),
    ('billing_config', 'disable_voucher_ai', 'boolean'),
    ('billing_config', 'activo', 'boolean'),
    ('recharge_requests', 'id', 'uuid'),
    ('recharge_requests', 'student_id', 'uuid'),
    ('recharge_requests', 'parent_id', 'uuid'),
    ('recharge_requests', 'school_id', 'uuid'),
    ('recharge_requests', 'amount', 'numeric'),
    ('recharge_requests', 'wallet_amount', 'numeric'),
    ('recharge_requests', 'payment_method', 'text'),
    ('recharge_requests', 'reference_code', 'text'),
    ('recharge_requests', 'voucher_url', 'text'),
    ('recharge_requests', 'notes', 'text'),
    ('recharge_requests', 'status', 'text'),
    ('recharge_requests', 'request_type', 'text'),
    ('recharge_requests', 'description', 'text'),
    ('recharge_requests', 'rejection_reason', 'text'),
    ('recharge_requests', 'approved_by', 'uuid'),
    ('recharge_requests', 'approved_at', 'timestamp with time zone'),
    ('recharge_requests', 'transaction_id', 'uuid'),
    ('recharge_requests', 'expires_at', 'timestamp with time zone'),
    ('recharge_requests', 'created_at', 'timestamp with time zone'),
    ('recharge_requests', 'lunch_order_ids', 'ARRAY'),
    ('recharge_requests', 'paid_transaction_ids', 'ARRAY'),
    ('recharge_requests', 'invoice_type', 'text'),
    ('recharge_requests', 'invoice_client_data', 'jsonb'),
    ('recharge_requests', 'voided_by', 'uuid'),
    ('recharge_requests', 'voided_at', 'timestamp with time zone'),
    ('recharge_requests', 'void_reason', 'text'),
    ('recharge_requests', 'expected_amount', 'numeric'),
    ('transactions', 'id', 'uuid'),
    ('transactions', 'student_id', 'uuid'),
    ('transactions', 'teacher_id', 'uuid'),
    ('transactions', 'school_id', 'uuid'),
    ('transactions', 'type', 'text'),
    ('transactions', 'amount', 'numeric'),
    ('transactions', 'description', 'text'),
    ('transactions', 'balance_after', 'numeric'),
    ('transactions', 'created_by', 'uuid'),
    ('transactions', 'created_at', 'timestamp with time zone'),
    ('transactions', 'ticket_code', 'text'),
    ('transactions', 'payment_status', 'text'),
    ('transactions', 'payment_method', 'text'),
    ('transactions', 'metadata', 'jsonb'),
    ('transactions', 'is_deleted', 'boolean'),
    ('transactions', 'paid_with_mixed', 'boolean'),
    ('transactions', 'cash_amount', 'numeric'),
    ('transactions', 'card_amount', 'numeric'),
    ('transactions', 'yape_amount', 'numeric'),
    ('transactions', 'document_type', 'character varying'),
    ('transactions', 'invoice_client_name', 'text'),
    ('transactions', 'invoice_client_dni_ruc', 'character varying'),
    ('transactions', 'invoice_id', 'uuid'),
    ('transactions', 'is_taxable', 'boolean'),
    ('transactions', 'billing_status', 'text'),
    ('transactions', 'billing_processing_at', 'timestamp with time zone'),
    ('transactions', 'payment_session_id', 'uuid'),
    ('transactions', 'gateway_reference_id', 'text'),
    ('transactions', 'gateway_transaction_id', 'text')
)
SELECT table_name, column_name, data_type
FROM schema_reference
ORDER BY table_name, column_name;
